{
 "title": "Rönd Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, k8sCluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(rond_policy_evaluation_duration_milliseconds_count{k8sCluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(rond_policy_evaluation_duration_milliseconds_count, service)"
    }
   },
   {
    "name": "policyName",
    "query": {
     "query": "label_values(rond_policy_evaluation_duration_milliseconds_count{service=~\"$service\"}, policy_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Policy Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Used policy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (policy_name)(increase(rond_policy_evaluation_duration_milliseconds_count{k8sCluster=\"$cluster\",namespace=\"$namespace\", policy_name=~\"$policyName\",service=~\"$service\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service to Policy mapping",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rond_policy_evaluation_duration_milliseconds_count{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service\",policy_name=~\"$policyName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$policyName evaluation time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "repeat": "policyName",
   "targets": [
    {
     "expr": "sum by (policyName,le) (increase(rond_policy_evaluation_duration_milliseconds_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",policy_name=\"$policyName\",service=~\"$service\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "CPU Usage $service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{k8sCluster=\"$cluster\", namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{k8sCluster=\"$cluster\", namespace=\"$namespace\", workload=\"$service\"}\n)\n",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{k8sCluster=\"$cluster\",namespace=\"$namespace\",container=\"rbac-service\",pod=~\"$service-.*\",resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{k8sCluster=\"$cluster\",namespace=\"$namespace\",container=\"rbac-service\",pod=~\"$service-.*\",resource=\"cpu\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$service-.*\", container=\"rbac-service\", k8sCluster=\"$cluster\"}[$__rate_interval])) by (container) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$service-.*\", container=\"rbac-service\", k8sCluster=\"$cluster\"}[$__rate_interval])) by (container)",
     "legendFormat": "Throttle"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 179 } },
  {
   "title": "Memory $service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{k8sCluster=\"$cluster\", namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{k8sCluster=\"$cluster\", namespace=\"$namespace\", workload=\"$service\"}\n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=\"rbac-service\", resource=\"memory\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=\"rbac-service\", resource=\"memory\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 204 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top used policy",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 214 },
     "targets": [
      {
       "expr": "sum by (policyName) (count_over_time({k8sCluster=\"$cluster\",namespace=\"$namespace\",container=\"rbac-service\",app_kubernetes_io_name=~\"$service\"} | json | msg = \"policy evaluation completed\" and policyName=~\"$policyName\" | __error__=\"\" [$__range]))",
       "legendFormat": "{{requestURL}}"
      }
     ]
    },
    {
     "title": "Policy/Path mapping",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 223 },
     "targets": [
      {
       "expr": "{k8sCluster=\"$cluster\",namespace=\"$namespace\",app_kubernetes_io_name=~\"$service\"} | json | msg = \"policy evaluation completed\" and policyName=~\"$policyName\" | __error__=\"\""
      }
     ]
    },
    {
     "title": "Evaluation time policy $policyName",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 233 },
     "repeat": "policyName",
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "max (max_over_time({k8sCluster=\"$cluster\",namespace=\"$namespace\",app_kubernetes_io_name=~\"$service\"} | json | msg = \"policy evaluation completed\" and policyName=\"$policyName\"  | unwrap evaluationTimeMicroseconds | __error__=\"\" [$__range])) by (namespace)",
       "legendFormat": "max latency"
      },
      {
       "expr": "quantile_over_time(0.95, {k8sCluster=\"$cluster\",namespace=\"$namespace\",app_kubernetes_io_name=~\"$service\"} | json | msg = \"policy evaluation completed\" and policyName=\"$policyName\" | unwrap evaluationTimeMicroseconds | __error__=\"\" [$__range]) by (namespace)",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "quantile_over_time(0.5, {k8sCluster=\"$cluster\",namespace=\"$namespace\",app_kubernetes_io_name=~\"$service\"} | json | msg = \"policy evaluation completed\" and policyName=\"$policyName\" | unwrap evaluationTimeMicroseconds | __error__=\"\" [$__range]) by (namespace)",
       "legendFormat": "50th percentile"
      }
     ]
    }
   ]
  }
 ]
}